const includeDeprecated = !process.env.ESLINT_CONFIG_PRETTIER_NO_DEPRECATED;

export type RuleValue = "off";

export const rules: Readonly<Record<string, RuleValue>> = {
  "curly": "off",
  "no-unexpected-multiline": "off",
  "@typescript-eslint/lines-around-comment": "off",
  "@typescript-eslint/quotes": "off",

  "@typescript-eslint/block-spacing": "off",
  "@typescript-eslint/brace-style": "off",
  "@typescript-eslint/comma-dangle": "off",
  "@typescript-eslint/comma-spacing": "off",
  "@typescript-eslint/func-call-spacing": "off",
  "@typescript-eslint/indent": "off",
  "@typescript-eslint/key-spacing": "off",
  "@typescript-eslint/keyword-spacing": "off",
  "@typescript-eslint/member-delimiter-style": "off",
  "@typescript-eslint/no-extra-parens": "off",
  "@typescript-eslint/no-extra-semi": "off",
  "@typescript-eslint/object-curly-spacing": "off",
  "@typescript-eslint/semi": "off",
  "@typescript-eslint/space-before-blocks": "off",
  "@typescript-eslint/space-before-function-paren": "off",
  "@typescript-eslint/space-infix-ops": "off",
  "@typescript-eslint/type-annotation-spacing": "off",

  ...(includeDeprecated && {
    "space-unary-word-ops": "off",
    "generator-star": "off",
    "no-comma-dangle": "off",
    "no-reserved-keys": "off",
    "no-space-before-semi": "off",
    "no-wrap-func": "off",
    "space-after-function-name": "off",
    "space-before-function-parentheses": "off",
    "space-in-brackets": "off",
    "no-arrow-condition": "off",
    "space-after-keywords": "off",
    "space-before-keywords": "off",
    "space-return-throw-case": "off",
    "no-spaced-func": "off",
    "indent-legacy": "off",
    "array-bracket-newline": "off",
    "array-bracket-spacing": "off",
    "array-element-newline": "off",
    "arrow-parens": "off",
    "arrow-spacing": "off",
    "block-spacing": "off",
    "brace-style": "off",
    "comma-dangle": "off",
    "comma-spacing": "off",
    "comma-style": "off",
    "computed-property-spacing": "off",
    "dot-location": "off",
    "eol-last": "off",
    "func-call-spacing": "off",
    "function-call-argument-newline": "off",
    "function-paren-newline": "off",
    "generator-star-spacing": "off",
    "implicit-arrow-linebreak": "off",
    "indent": "off",
    "jsx-quotes": "off",
    "key-spacing": "off",
    "keyword-spacing": "off",
    "linebreak-style": "off",
    "lines-around-comment": "off",
    "max-len": "off",
    "max-statements-per-line": "off",
    "multiline-ternary": "off",
    "new-parens": "off",
    "newline-per-chained-call": "off",
    "no-confusing-arrow": "off",
    "no-extra-parens": "off",
    "no-extra-semi": "off",
    "no-floating-decimal": "off",
    "no-mixed-operators": "off",
    "no-mixed-spaces-and-tabs": "off",
    "no-multi-spaces": "off",
    "no-multiple-empty-lines": "off",
    "no-tabs": "off",
    "no-trailing-spaces": "off",
    "no-whitespace-before-property": "off",
    "nonblock-statement-body-position": "off",
    "object-curly-newline": "off",
    "object-curly-spacing": "off",
    "object-property-newline": "off",
    "one-var-declaration-per-line": "off",
    "operator-linebreak": "off",
    "padded-blocks": "off",
    "quote-props": "off",
    "quotes": "off",
    "rest-spread-spacing": "off",
    "semi": "off",
    "semi-spacing": "off",
    "semi-style": "off",
    "space-before-blocks": "off",
    "space-before-function-paren": "off",
    "space-in-parens": "off",
    "space-infix-ops": "off",
    "space-unary-ops": "off",
    "switch-colon-spacing": "off",
    "template-curly-spacing": "off",
    "template-tag-spacing": "off",
    "wrap-iife": "off",
    "wrap-regex": "off",
    "yield-star-spacing": "off",
  }),
};

Object.freeze(rules);

export default { rules };
